project_id = "tlfnpkhwxmcajklkozor"

[functions.create-payment]
verify_jwt = false

[functions.get-channels]
verify_jwt = false

[functions.payment-callback]
verify_jwt = false

[functions.validate-callback]
verify_jwt = false

[functions.user-create-payment]
verify_jwt = false

[functions.get-transaction-by-ref]
verify_jwt = false

[functions.check-transaction]
verify_jwt = false

[functions.sanpay-webhook]
verify_jwt = false

[functions.expire-transactions]
verify_jwt = false

[functions.provider-webhook]
verify_jwt = false

